const $=x=>document.querySelector(x), U='暂不明确|';
const D={hardware:{w:.4,a:[['privacy','独立性',['整租 / 独卫|4','独立卧室 / 共卫|2.8','合租床位|1.5',U]],['orientation','朝向采光',['东南 / 南向|4','东向|3','西向|2','北向|1',U]],['area','面积与户型',['宽裕、布局合理|4','够用|3','局促|1.5',U]],['cooking','做饭条件',['独立厨房，可明火|4','可做饭但受限|2.5','无法做饭|1',U]],['sound','室内隔音',['实墙、安静|4','可接受|3','明显串音|1.5',U]],['drain','排污系统',['正常下水|4','偶有异味|2.5','污水粉碎机马桶|1|排污系统高风险',U]],['water','热水供应',['稳定 24 小时|4','定时 / 储水式|2.5','不稳定|1',U]]]},commute:{w:.3,a:[['time','门到门单程时间',['30 分钟内|4','31–45 分钟|3','46–60 分钟|2','60 分钟以上|1',U]],['transfer','接驳便利',['步行 / 骑行直达|4','一次换乘|3','多次换乘|1.5',U]],['safety','社区安防',['门禁、物业完善|4','基本门禁|3','出入开放|1.5',U]],['amenity','生活配套',['步行可达齐全|4','基本齐全|3','不方便|1.5',U]],['sanitation','垃圾点与环境卫生',['干净、管理及时|4','偶有翻捡或散落|2.5','频繁翻捡、异味或脏乱|1',U]],['noise','外部环境噪音',['安静|4','偶有噪音|3','长期吵闹|1',U]]]},finance:{w:.3,a:[['rent','月度住房负担',null],['deposit','押付方式',['押一付一 / 押一付三|4','半年付|2.5','年付 / 租金贷|1|长期预付或租金贷风险高',U]],['party','签约主体',['房东直租|4','正规中介|3','二房东|1.5',U]],['utility','水电性质',['民水民电|4','商水或商电|2','水电明显高价|1',U]]]}};
D.hardware.a[3][2]=['独立厨房、排烟良好|4','电磁炉等安全烹饪条件|3.5','共用或受限厨房|2.5','无法做饭|1.5',U];
D.hardware.a.splice(4,0,['fire','燃气与消防安全',['无燃气隐患、通风与报警可靠|4','设施正常，待复核|2.5','老旧燃气 / 通风差 / 私接明火|1|燃气或明火存在安全风险',U]]);
const P=x=>{let[a,b,c]=x.split('|');return{a,b:b===''?null:+b,c}};let active=0;const H=['房源 A','房源 B','房源 C'].map((name,i)=>({name,rent:0,v:Object.fromEntries(Object.values(D).flatMap(d=>d.a).map(([k,,o])=>[k,k==='rent'?0:i===2?o.length-1:Math.min(i,o.length-1)]))}));
function cost(h){let income=+$('#income').value;if(!h.rent||!income)return null;let e=(+$('#kwh').value||0)*(+$('#electricPrice').value||0),w=(+$('#waterM3').value||0)*(+$('#waterPrice').value||0),total=h.rent+e+w+(+$('#hotWaterCost').value||0)+(+$('#internetCost').value||0)+(+$('#transitCost').value||0),r=total/income,rentRatio=h.rent/income,t={0:.30,1:.28,2:.26,3:.24,4:.22}[$('#tier').value],s=r>.4?1.2:r<=.8*t?4:r<=t?3.5:r<=1.2*t?2.5:1.5;return{r,rentRatio,t,s,total,e,w,risk:r>.4?'月度住房负担率超过 40%，现金流压力过高':''}}
function score(h){let sum=0,w=0,r=[];for(let d of Object.values(D)){let a=[];for(let[k,,o]of d.a){if(k==='rent'){let z=cost(h);if(z){a.push(z.s);if(z.risk)r.push(z.risk)};continue}let z=P(o[h.v[k]]);if(z.b!==null)a.push(z.b);if(z.c)r.push(z.c)}if(a.length){sum+=d.w*a.reduce((x,y)=>x+y,0)/a.length;w+=d.w}}let cap=r.some(x=>x.includes('排污'))?1.8:r.some(x=>x.includes('预付'))?1.5:r.some(x=>x.includes('负担率'))?1.2:5;return{n:Math.min(cap,w?sum/w:0),r}}
function render(){let h=H[active];$('#tabs').innerHTML=H.map((x,i)=>`<button data-i="${i}" class="${i===active?'active':''}">${x.name}</button>`).join('');document.querySelectorAll('[data-i]').forEach(x=>x.onclick=()=>{active=+x.dataset.i;render()});for(let[n,d]of Object.entries(D)){$('#'+n).innerHTML=d.a.map(([k,l,o])=>`<div class="metric"><label>${l}</label>${k==='rent'?`<input data-rent type="number" min="0" value="${h.rent}">`:`<select data-k="${k}">${o.map((x,i)=>{let z=P(x);return`<option value="${i}" ${h.v[k]===i?'selected':''}>${z.a}${z.b!==null?' · '+z.b+' 分':''}</option>`}).join('')}</select>`}</div>`).join('')}let e=score(h),c=cost(h);$('#summary').innerHTML=`<strong>${e.n.toFixed(1)}</strong><div><h2>${e.r.length?'高风险：不建议签约':'综合性价比评估'}</h2><p>${c?`月度住房负担率 ${(c.r*100).toFixed(1)}%，本城市建议线 ${(c.t*100).toFixed(0)}%。`:''}</p></div>`;$('#risk').hidden=!e.r.length;$('#risk').textContent='⚠ '+e.r.join('；');document.querySelectorAll('[data-k]').forEach(x=>x.onchange=()=>{h.v[x.dataset.k]=+x.value;render()});$('[data-rent]').oninput=x=>{h.rent=+x.target.value;render()}}
['income','tier','kwh','electricPrice','waterM3','waterPrice','hotWaterCost','internetCost','transitCost'].forEach(x=>$('#'+x).oninput=render);
const baseScore=score;score=h=>{const result=baseScore(h);if(result.r.some(x=>x.includes('燃气')))result.n=Math.min(result.n,1.5);return result};
D.finance.a[0][1]='月租金（元）';
D.finance.a[1][2]=['月付（无押金）|4','押一付一|3.3','押一付三|2.5','半年付|2','年付 / 租金贷|1|长期预付或租金贷风险高',U];
const originalRender=render;render=()=>{originalRender();const h=H[active],c=cost(h),rent=$('#activeRent');rent.value=h.rent||'';rent.oninput=e=>{h.rent=+e.target.value};rent.onchange=render;const oldRent=$('[data-rent]');if(oldRent)oldRent.closest('.metric').style.display='none';if(c){$('#summary').insertAdjacentHTML('beforeend',`<div class="cost-detail">房租收入比：<b>${(c.rentRatio*100).toFixed(1)}%</b>　综合月成本：<b>¥${c.total.toFixed(0)}</b><br><small>其中电费 ¥${c.e.toFixed(0)}，水费 ¥${c.w.toFixed(0)}；综合负担率 ${(c.r*100).toFixed(1)}%，建议线 ${(c.t*100).toFixed(0)}%。</small></div>`);}};render();
